### ISSUE TITLE
Tab as delimiter does not work.

### ISSUE THREAD

**Issue by ben221199** [emersion/go-imap#408] opened 2020-11-27 14:34 UTC
Hello all,

First of all, what a great project.
However, I have some problems with a custom delimiter.

When I have `/` as delimiter, it will be like this:
![image](https://user-images.githubusercontent.com/12856904/100459148-4472d900-30c5-11eb-819f-cb9569bd3771.png)

But when I change it to a tab (`	`), then it will be like this:
![image](https://user-images.githubusercontent.com/12856904/100459278-81d76680-30c5-11eb-83a4-b8480706471c.png)

This will break clients like Thunderbird.
Note that every character is allowed as delimiter except `0x00`, but if you want `"` or `\`, it should have an extra `\` before it.

**Comment by ben221199** [comment] 2020-11-27 14:44
I also tried other delimiters than the tab and all characters I tried where in the range of 0x01-x07F, but in Thunderbird all my folders disappeared.

**Comment by emersion** [comment] 2023-04-04 14:03
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed by emersion** 2023-04-04 14:03 UTC
