### ISSUE TITLE
Race conditions while trying to select INBOX

### ISSUE THREAD

**Issue by FelixPodint** [emersion/go-imap#440] opened 2021-09-02 09:03 UTC
Hi,

I'm creating a basic mail client for our organization and everything was going smooth until one of my co-workers added a mail.ru account with another mail.ru account linked to it (if adding Gmail account in place of mail.ru everything seams to work file), at which point my program hangs and no errors are produced.

After step-by-step debugging, I found out that:
* My code stops at mbox, e := conn.Select("INBOX", true) call; [conn is *client.Client]
* Moving deeper from conn.Select(...) into go-imap library: 
  * conn.Select(...) -> 
  * status, err := c.execute(cmd, res)[46:20] -> 
  * c.registerHandler(responses.HandlerFunc(func(resp imap.Resp) error {...}[210:5] -> 
  * c.handlersLocker.Lock()[110:5] -> 
  * m.lockSlow()[81:5];
* m.lockSlow()[81:5] newer returns (did not go any deeper);
* It seams something is preventing Mutex from locking;

I'm not sure if this is a library problem or mail.ru internal problem.

Thanks.
Felix P.

**Comment by fronge** [comment] 2022-03-28 05:41
use pprof,show:
#	0xedf113	github.com/emersion/go-imap/client.(*Client).execute+0x3d3	/root/go/pkg/mod/github.com/emersion/go-imap@v1.1.0/client/client.go:276
#	0xee10e4	github.com/emersion/go-imap/client.(*Client).Select+0x1e4	/root/go/pkg/mod/github.com/emersion/go-imap@v1.1.0/client/cmd_auth.go:46

**Comment by emersion** [comment] 2023-04-04 14:02
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed by emersion** 2023-04-04 14:02 UTC
