### ISSUE TITLE
parse email body error

### ISSUE THREAD

**Issue by liudijing07** [emersion/go-imap#479] opened 2022-11-03 13:27 UTC
i found something wrong like this:

imap/client: 2022/11/03 21:07:59 error reading response: expected a space
imap/client: 2022/11/03 21:07:59 error reading response: fields are not separated by a space
imap/client: 2022/11/03 21:07:59 error reading response: atom contains forbidden char: "
imap/client: 2022/11/03 21:07:59 error reading response: line doesn't end with a CR
imap/client: 2022/11/03 21:07:59 error reading response: expected a space
imap/client: 2022/11/03 21:07:59 error reading response: quoted string cannot contain backslash followed by a non-quoted-specials char
imap/client: 2022/11/03 21:07:59 error reading response: expected a space
imap/client: 2022/11/03 21:07:59 error reading response: fields are not separated by a space
imap/client: 2022/11/03 21:07:59 error reading response: atom contains forbidden char: "
imap/client: 2022/11/03 21:07:59 error reading response: line doesn't end with a CR
imap/client: 2022/11/03 21:07:59 error reading response: expected a space
imap/client: 2022/11/03 21:07:59 error reading response: quoted string cannot contain backslash followed by a non-quoted-specials char
imap/client: 2022/11/03 21:07:59 error reading response: expected a space

the mail body 
![image](https://user-images.githubusercontent.com/39851989/199732146-08ef6284-deb0-4e7a-be41-cad45dc96b10.png)

![image](https://user-images.githubusercontent.com/39851989/199732876-0d053cb0-7105-4bd8-9fd3-4b71324e536f.png)

can you help me

**Comment by liudijing07** [comment] 2022-11-04 10:23
i try to fix it, and i think it wrok well

**Comment by emersion** [comment] 2023-04-04 14:00
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed as completed by emersion** 2023-04-04 14:00 UTC
