### ISSUE TITLE
"Could not parse command" error when resend an "IDLE" command immediately after closing "IDLE"

### ISSUE THREAD

**Issue by alexei-bykovski** [emersion/go-imap#486] opened 2023-02-14 13:33 UTC
Periodically I have an error "Could not parse command" when I'm trying to resend an 'IDLE' command after closing "IDLE" every 20 min (RFC 2177 recommends 29 min max). It seems like it happens because idling is not closed before sending a new "IDLE" command. If I add a sleep like `time.Sleep(10 * time.Millisecond)` between close and resend "IDLE" everything works fine. 
```
func (conns *Conns) idle(ci *ConnItem, lbl *MboxLabel) error {
	c, err := conns.GetConn(ci, lbl)

	// Create a channel to receive mailbox updates
	updates := make(chan imapClient.Update)
	c.Updates = updates

	done := make(chan error, 1)
	ci.Idle[lbl.Name] = make(chan struct{}, 1)
	go func() {
		done <- c.Idle(ci.Idle[lbl.Name], nil)
	}()

	resetTicker := time.NewTicker(20 * time.Minute)

	for {
		select {
		case <-resetTicker.C:
			// Reset idle (RFC 2177 recommends 29 min max)
			close(ci.Idle[lbl.Name])
			// If put here `time.Sleep(10 * time.Millisecond)` line
			// everything works fine, otherwise "Idle" command returns error "Could not parse command"
			return conns.Idle(ci, lbl)
		case err = <-done:
			return err
		}
	}
}
```

**Comment by emersion** [comment] 2023-04-04 14:03
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed as completed by emersion** 2023-04-04 14:03 UTC
