### ISSUE TITLE
problem parsing headers

### ISSUE THREAD

**Issue by GswOne** [emersion/go-imap#452] opened 2021-11-18 19:28 UTC
I found a problem with parsing the message headers:

example: (a piece of header)
Date: Thu, 18 Nov 2021 07:39:38 +0000
Message-ID:
 <VE1P191MB08618D22D19@VE.PROD.OUTLOOK.COM>
References: <emd7ec0300-0ff0-4107@xxx>

Message-ID translation is incorrect. In this case empty.

the problem is highlighted here: (message.go)

// Parse an envelope from fields.
func (e *Envelope) Parse(fields []interface{}) error {
[..]

	if msgId, ok := fields[9].(string); ok {	<-- field[9] in NOT a string, contains: 
                                                    "/n <VE1P191MB08618D22D19@VE.PROD.OUTLOOK.COM>"
		e.MessageId = msgId
	}

**Comment by emersion** [comment] 2021-11-19 09:23
I'm confused. If `fields[9]` is not a string, what is it? Can you print its type with `log.Printf("%T", fields[9])`?

**Comment by GswOne** [comment] 2021-11-22 11:45
debugger show me as []byte


Il giorno ven 19 nov 2021 alle ore 10:23 Simon Ser ***@***.***>
ha scritto:

**Comment by emersion** [comment] 2023-04-04 14:01
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed by emersion** 2023-04-04 14:01 UTC
