### ISSUE TITLE
UidFetch not closing channel?

### ISSUE THREAD

**Issue by glennzw** [emersion/go-imap#353] opened 2020-04-21 18:50 UTC
I have the following code which works fine to search for new email by sequence numbers:

### Code:
```
// Search for unread emails
criteria := imap.NewSearchCriteria()
criteria.WithoutFlags = []string{"\\Seen"}
seqs, err := imapclient.Search(criteria)
fmt.Println("Messages: ", seqs)

seqset := new(imap.SeqSet)
seqset.AddNum(seqs...)
section := &imap.BodySectionName{}
items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate, section.FetchItem()} 
messages := make(chan *imap.Message)


go func() {
	if err := imapclient.Fetch(seqset, items, messages); err != nil {
		log.Println("Error fetching emails: ", err.Error())
	}
}()

for msg := range messages {
   fmt.Printf("Message UID, SeqNun, Size: (%d, %d, %d)\n", msg.Uid, msg.SeqNum, msg.Size)
}
fmt.Println("Done")
```

### Output:
```
Messages: [123 124]
Message UID, SeqNun, Size: (0, 123, 0)
Message UID, SeqNun, Size: (0, 124, 0)
Done
```

Now, I want to search by UID rather than sequence number, so I make two changes: 

` imapclient.Search` to ` imapclient.UidSearch`
`imapclient.Fetch` to `imapclient.UidFetch`

The output from this small change results in the code never reaching the "Done" statement:

### Output:
```
Messages: [131 135]
Message UID, SeqNun, Size: (131, 123, 0)
Message UID, SeqNun, Size: (135, 124, 0)
Message UID, SeqNun, Size: (131, 123, 0)
```

Also, strangely, it processes the first email again (UID 131).

Could anyone shed some light for me? Looks similar to this issue https://github.com/emersion/go-imap/issues/253 but there are no replies.

**Comment by glennzw** [comment] 2020-04-22 11:58
Debugging further, it seems to be the `imap.BodySectionName{}` that results in the block when using the `UidFetch`:

```
// This blocks when using UidFetch, and does not return:
section := &imap.BodySectionName{}
items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate, section.FetchItem()} // Check this

// But this is fine, and returns
// items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate}

go func() {
	done <- c.UidFetch(seqset, items, messages)
}()

for msg := range messages {
	log.Println("* " + msg.Envelope.Subject)
}
```

Changing `UidFetch` to just `Fetch` when grabbing the body section works fine though.

### Full code:
```
package main

import (
	"log"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
)

func main() {
	log.Println("Connecting to server...")

	// Connect to server
	c, err := client.DialTLS("imap.gmail.com:993", nil)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")

	// Don't forget to logout
	defer c.Logout()

	// Login
	if err := c.Login("username", "password"); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")

	// Select INBOX
	c.Select("INBOX", false)

	// Search for unread emails
	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{"\\Seen"}
	seqs, err := c.UidSearch(criteria)
	//seqs2, err := imapclient.UidSearch(criteria)
	if err != nil {
		panic(err)
	}

	if len(seqs) > 0 {
		log.Println("New emails UIDS: ", seqs)
		seqset := new(imap.SeqSet)
		seqset.AddNum(seqs...)

		// This blocks, and does not return:
		section := &imap.BodySectionName{}
		items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate, section.FetchItem()} // Check this

		//This is fine, and returns
		//items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchFlags, imap.FetchInternalDate}

		messages := make(chan *imap.Message)

		done := make(chan error, 1)
		go func() {
			done <- c.UidFetch(seqset, items, messages)
		}()

		log.Println("New messages:")

		for msg := range messages {
			log.Println("* " + msg.Envelope.Subject)
		}

		if err := <-done; err != nil {
			log.Fatal(err)
		}
	} else {
		log.Println("No new emails")
	}

	log.Println("Done!")
}

```

### Output:
```
2020/04/22 12:57:41 Connecting to server...
2020/04/22 12:57:41 Connected
2020/04/22 12:57:42 Logged in
2020/04/22 12:57:43 New emails UIDS:  [131 135]
2020/04/22 12:57:43 New messages:
2020/04/22 12:57:43 * fwd: test
2020/04/22 12:57:43 * here's a test
```

(Never reaching the desired "Done" statement and exiting)

**Comment by glennzw** [comment] 2020-04-22 14:08
Additional info;

 * The Uid blocking condition was tested with GMail, trying now with Outlook IMAP servers and it's fine
 * The Uid fetch causes a segfault if there's only one email in the GMail inbox, but not with Outlook

**Comment by glennzw** [comment] 2020-04-22 14:22
Update:

I found a post from [2012](https://support.google.com/mail/forum/AAAAK7un8RUj-snr8u0p6s/?hl=en-GB) of someone having a similar issue with GMail, the suggestion being to send a NOOP (no op) command to the server. This has fixed the issue. 

```
go func() {
	done <- c.Fetch(seqset, items, messages)
}()

c.Noop()
```

**Comment by emersion** [comment] 2020-04-22 14:47
Can you obtain debug logs with `Client.SetDebug(os.Stdout)`?

**Comment by glennzw** [comment] 2020-04-22 15:08
Attached are the debugging outputs from UidSearch/UidFetch vs Search/Fetch when using GMail. 


[non_uid_mode.txt](https://github.com/emersion/go-imap/files/4516945/non_uid_mode.txt)
[uid_mode.txt](https://github.com/emersion/go-imap/files/4516947/uid_mode.txt)

It looks like the logout command is missing from the Uid mode.

**Comment by glennzw** [comment] 2020-04-22 15:09
Attached are the debugging outputs from UidSearch/UidFetch vs Search/Fetch when using GMail.

[non_uid_mode.txt](https://github.com/emersion/go-imap/files/4516965/non_uid_mode.txt)
[uid_mode.txt](https://github.com/emersion/go-imap/files/4516966/uid_mode.txt)


It looks like the logout command is missing from the Uid mode.

**Comment by glennzw** [comment] 2020-04-22 15:19
If it's of use here's the debug output from Outlook - which succeeds for both Uid and non-Uid operations.

[non_uid_mode_outlook.txt](https://github.com/emersion/go-imap/files/4517033/non_uid_mode_outlook.txt)
[uid_mode_outlook.txt](https://github.com/emersion/go-imap/files/4517034/uid_mode_outlook.txt)

**Comment by glennzw** [comment] 2020-04-22 15:27
Also, here are the logs from GMail when searching/fetching via UID when there is only one unread email in the inbox - the segfault condition.

[gmail_one_email_nonuid_success.txt](https://github.com/emersion/go-imap/files/4517061/gmail_one_email_nonuid_success.txt)
[gmail_one_email_uid_segfault.txt](https://github.com/emersion/go-imap/files/4517062/gmail_one_email_uid_segfault.txt)

**Comment by glennzw** [comment] 2020-04-27 19:32
Any luck investigating @emersion , or anything else I can help with?

**Comment by glennzw** [comment] 2020-05-07 12:59
I have a working hack, rather than iterating over the messages channel, we can just pop the expected number of new messages:

```
for i := range seqs {
	msg := <-messages
	log.Println("* " + msg.Envelope.Subject)
}
```

Seems I need to skip the `c.Logout()` otherwise the program never terminates.

Not ideal, will keep trying to figure out the root cause.

**Comment by DZariusz** [comment] 2020-05-15 08:17
I have same issue, but above tricks doesn't work for me.

```
seqset := new(imap.SeqSet)
seqset.AddRange(from, to)

messages := make(chan *imap.Message)
done := make(chan error, 1)
items := []imap.FetchItem{imap.FetchEnvelope, imap.FetchRFC822}

go func() {
  logger.Debug("go func()...")
  //done <- c.Fetch(seqset, items, messages)
  done <- c.UidFetch(seqset, items, messages)

  logger.Debug("does not matter if I use Fetch or UidFetch, code never reach here")
}()

// its hang and never get out of `go func()`, need to use `ctrl+C` to stop it.
```

`Client.SetDebug(os.Stdout)` logs for two cases:

[go-imap-case1.log](https://github.com/emersion/go-imap/files/4633070/go-imap-case1.log)
[go-imap-case2.log](https://github.com/emersion/go-imap/files/4633071/go-imap-case2.log)

`go-imap-case2.log` is not cutted at the end - it's how its logged.

```
# go.mod
go 1.14

require (
	github.com/emersion/go-imap v1.0.4
	github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21
	github.com/gobuffalo/packr/v2 v2.8.0
	github.com/gorilla/mux v1.7.4
	github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
	golang.org/x/net v0.0.0-20200513185701-a91f0712d120
	golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
	google.golang.org/api v0.24.0
)
```

**Comment by glennzw** [comment] 2020-05-15 12:35
@DZariusz It looks like you're connecting to an Apple mailserver? If so, this would mean:

GMail: ❌
Apple: ❌
Outlook: ✅

**Comment by DZariusz** [comment] 2020-05-15 14:09
@glennzw I'm using generic mailserver on shared hosting, not Apple. I tried also Gmail - no luck. 
I created Outlook account just to see if it will be working for me. It work-ish... `c.UidFetch` finalising `FETCH` command with success but stack in `go func()` as described in my previous comment. `c.Fetch` ends with error command but also stuck.

[go-imap-outlook.com-fetch.log](https://github.com/emersion/go-imap/files/4634819/go-imap-outlook.com-fetch.log)

**Comment by msmarino** [comment] 2020-11-25 19:47
I may be suffering from problems related to this issue:

for testing I send and receive to the same account...  tested with gmail, outlook, yahoo and VPS with postfix

Mostly, but not exclusively, the library seems to hang after `Fetch`ing an email body.  full debug logs attached.

basic process:
- open connection with idle
- create sender go routine (sends continuous emails...)
- open worker connection
- on receipt of MailboxUpdate, with worker
  - search using text
  - recover subjects
  - recover mails
  - delete mails

At the end of the log the fetch does not return but sending continues...

There seems to be no pattern.  Sometimes running whole 2min without failures, others failing on second receipt.

[TestConnection.log](https://github.com/emersion/go-imap/files/5598890/TestConnection.log)

**Comment by emersion** [comment] 2020-11-26 16:48
>create sender go routine

You can't use the same `imap.Client` from multiple goroutines.

**Comment by msmarino** [comment] 2020-11-26 18:06
Sorry.  Lack of clearness on my behalf.  

I am using 2 different connections, the idler, and the worker.  Updates from the idler are acted upon by the worker.

I've been refactoring my code and now I have a race within the library, specifically in the client.Select()

[TestConnection3.log](https://github.com/emersion/go-imap/files/5604496/TestConnection3.log)

**Comment by croemmich** [comment] 2021-03-19 18:26
I'm seeing the same issue as described by @glennzw. Dug in a little bit, but can't figure out what's going on yet.

**Comment by ivy-yao** [comment] 2021-05-15 09:09
I just solved the problem, just add `imap.FetchUid` to c.Fetch arguments.
like:
`go func() {
		done <- c.Fetch(seqset, []imap.FetchItem{imap.FetchUid, sect.FetchItem()}, messages)
	}()
for msg := range messages {
		fmt.Printf("this is uid:", msg.Uid)
}
`

**Comment by emersion** [comment] 2023-04-04 14:04
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed by emersion** 2023-04-04 14:04 UTC
