### ISSUE TITLE
Fetch error in Goroutines, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghost** [emersion/go-imap#645] opened 2024-09-26 06:49 UTC
Hi Salut, I'm facing this issue.
Here is my error below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xc8054]

goroutine 2214 [running]:
io.discard.ReadFrom({}, {0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:666 +0x54
io.copyBuffer({0x355de0, 0x61d100}, {0x0, 0x0}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
github.com/emersion/go-imap/v2/imapclient.FetchItemDataBodySection.discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:324
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).Next(0xc0000bd4a0)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:253 +0x46
github.com/emersion/go-imap/v2/imapclient.(*FetchMessageData).discard(...)
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:263
created by github.com/emersion/go-imap/v2/imapclient.(*Client).handleFetch.func1 in goroutine 5
        C:/Users/Administrator/go/pkg/mod/github.com/emersion/go-imap/v2@v2.0.0-beta.3/imapclient/fetch.go:498 +0x178
exit status 2
```

I'm trying to return FetchItemDataBodySection inside a Goroutines. I already checked if body_section.Literal is nil but I'm still getting the same error.

```
literal := body_section.Literal
if literal == nil {
return
}
```

Here is my code below

```
all_seq_nums := result.AllSeqNums()
count := len(all_seq_nums)
if count > 0 {
  thread, _ := strconv.Atoi(thread)
  semaphore := make(chan struct{}, thread)
  var wg sync.WaitGroup

  for seq_num := uint32(0); seq_num < uint32(count) ; seq_num++ {
    wg.Add(1)
    semaphore <- struct{}{}
    go func(seq_num uint32) {
      defer wg.Done()
      defer func() { <-semaphore }()

      seq_set := imap.SeqSetNum(all_seq_nums[seq_num])
      fetch_options := &imap.FetchOptions{
        BodySection: []*imap.FetchItemBodySection{{}},
      }
      fetch_cmd := client.Fetch(seq_set, fetch_options)
      if fetch_cmd == nil {
        return
      }

      msg := fetch_cmd.Next()
      if msg == nil {
        fmt.Print("\n[-]  Message not found, skipping...")
        return
      }

      var body_section imapclient.FetchItemDataBodySection
      ok := false
      for {
        item := msg.Next()
        if item == nil {
          break
        }
        body_section, ok = item.(imapclient.FetchItemDataBodySection)
        if ok {
          break
        }
      }

      if ok {
        literal := body_section.Literal
        if literal == nil {
          return
        }

        mr, err := mail.CreateReader(literal)
        if err == nil {
          for {
            p, err := mr.NextPart()
            if err == io.EOF {
              break
            }

            switch p.Header.(type) {
            case *mail.InlineHeader:
              b, _ := io.ReadAll(p.Body)
              parse_message(string(b), imap_credential, mailbox_folder, all_seq_nums[seq_num])
            }
          }
        }
      }
      
      fetch_cmd.Close()
    }(seq_num)
  }

  wg.Wait()
}
```

**Comment by emersion** [comment] 2024-09-26 07:07
Duplicate of https://github.com/emersion/go-imap/issues/644

**Closed as completed by emersion** 2024-09-26 07:07 UTC
