### ISSUE TITLE
Missing error handling in client.

### ISSUE THREAD

**Issue by tomarus** [emersion/go-imap#92] opened 2017-01-04 10:33 UTC
Hi,

I believe there is a missing error handler somewhere during client read()'s.

This function sometimes returns an error:
https://github.com/emersion/go-imap/blob/master/client/client.go#L68

Like here: 
https://github.com/emersion/go-imap/blob/master/client/client.go#L107

But the returned error seems not handled here:
https://github.com/emersion/go-imap/blob/master/client/client.go#L257

When an error occurs (i.e. a network timeout) the client just hangs/waits forever.

Thanks for looking into this.

**Comment by emersion** [comment] 2017-01-04 11:23
When there is a network timeout, the `read` function returns with a network error (`error reading response: read tcp XXX->YYY: i/o timeout`). This function also closes all command handlers so `handleUnilateral` exits.

When you execute an IMAP command after a network timeout, an error is also returned (`imap: connection closed`).

If you want to know when a connection is closed, you can use `Client.LoggedOut()`.

**Comment by tomarus** [comment] 2017-01-04 16:21
I really doubt if all network errors are handled. I've seen a Fetch() hanging for over 24hr without any activity. 

Since network errors are hard to reproduce i figured it was the missing error handling i mentioned in the start post. But it could be something totally different ofcourse.

A way to customize client timeouts would be nice to have too.

I'll try to make a nice testcase to reproduce the hangs i'm seeing. I'll open a new issue when i got that (can take some time).

Thanks for your comments!

**Comment by emersion** [comment] 2017-01-04 17:24
Okay, I'll reopen this issue for now. If the client hangs up, you can press <kbd>Ctrl</kbd> + <kbd>\\</kbd> on Linux/macOS to see which goroutines are running. Let me know if you manage to reproduce!

You can set a client timeout using [`Client.Timeout`](https://godoc.org/github.com/emersion/go-imap/client#Client.Timeout).

**Comment by tomarus** [comment] 2017-01-04 20:47
Thank you kindly for your info, probably Client.Timeout is all we needed after all.

I'll still try looking into this issue in the next week or two see if i can reproduce it.

**Comment by emersion** [comment] 2017-03-10 08:09
Closing because of age, feel free to reopen if you have news.

**Closed by emersion** 2017-03-10 08:09 UTC
Labels: bug, client, question
