### ISSUE TITLE
How i can add MaxLiteralSize to mail.CreateReader? 

### ISSUE THREAD

**Issue by Krevedos** [emersion/go-imap#481] opened 2022-11-05 18:45 UTC
Memory leak by ReadLiteral method, I think it has to do with the size of the literal, but I don't know how to use it, please help. THX

![profile015](https://user-images.githubusercontent.com/26144119/200135853-ca2ac898-08cf-446a-9034-cf6f1950222c.png)

**Comment by emersion** [comment] 2023-04-04 14:01
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed as completed by emersion** 2023-04-04 14:01 UTC
