### ISSUE TITLE
Error in flags escaping in command STORE?

### ISSUE THREAD

**Issue by ciror14** [emersion/go-imap#433] opened 2021-05-13 19:12 UTC
I'm using a go product that is using go-imap v1.0.4 (although I checked and it seems that there is no difference in the latest version in the relevant part of code). The product tries to set some emails to deleted by calling 

	err = imapClient.Store(seqSet, item, imap.DeletedFlag, nil)

and the IMAP server (dovecot 2.2.36) returns the following error

BAD Error in IMAP command STORE: Flags list contains non-atoms

By looking at the TCPdump below, between the product and the imap server, it seems the `\Deleted` flag reaches the server with a wrong quoting:

``` 
uY5o8Q SELECT INBOX
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
* OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
* 155 EXISTS
* 0 RECENT
* OK [UIDVALIDITY 1598858752] UIDs valid
* OK [UIDNEXT 1608] Predicted next UID
uY5o8Q OK [READ-WRITE] Select completed (0.004 + 0.000 + 0.005 secs).
1JFupg STORE 154:155 +FLAGS.SILENT "\\Deleted"
1JFupg BAD Error in IMAP command STORE: Flags list contains non-atoms (0.001 + 0.000 secs).
ZWHJyw LOGOUT
* BYE Logging out
```

**Comment by Necoro** [comment] 2021-05-18 21:19
The problematic part is:
```go
// TODO: this could break extensions (this only works when item is FLAGS)
if fields, ok := value.([]interface{}); ok {
	for i, field := range fields {
		if s, ok := field.(string); ok {
			fields[i] = imap.RawString(s)
		}
	}
}
```
This marks strings as raw iff they are passed as an array (the client used by @ciror14 passes it directly).

I see two approaches:

1. put an `if _, _, err := imap.ParseFlagsOp(item); err == nil` around the for loop and then add the RawString-wrapper also for pure strings. This eliminates the TODO, but I don't know about possible side effects
2. add the `if` only together with the new RawString-wrapper. Fixes the bug w/o side-effects, but the code is then somewhat inconsistent.
3. mark the flag constants directly as RawStrings. Clean solution for the error at hand, but no solution for generic flags. (Also some larger refactoring might be the result due to the type change)
4. change the documentation to require flags to be passed as an array (plus perhaps an error if it is not the case).

I personally prefer 1. @emersion: Thoughts?

**Comment by ciror14** [comment] 2021-05-19 11:29
Thanks. About 4, how would I change the code ```err = imapClient.Store(seqSet, item, imap.DeletedFlag, nil)``` to pass it as an array?

**Comment by ciror14** [comment] 2021-05-19 11:53
Thanks!

**Comment by emersion** [comment] 2023-04-04 14:04
Closing because this is an issue about go-imap v1. I'm now focusing on go-imap v2.

Please re-open if you can reproduce with go-imap v2.

**Closed by emersion** 2023-04-04 14:04 UTC
Labels: bug
