### ISSUE TITLE
The bug for run the server

### ISSUE THREAD

**Issue by GZxiaoBinHuang** [emersion/go-imap#238] opened 2019-04-18 10:16 UTC
Some bugs arises running the server as below:
```# github.com/emersion/go-imap/backend/backendutil
../src/github.com/emersion/go-imap/backend/backendutil/search.go:80:32: invalid operation: e.Header.Header[key] (type "github.com/emersion/go-message/textproto".Header does not support indexing)
```

I check the search.go:80:32, and it says that the type of the e.Header is 
```
type Header struct {
	// Fields are in reverse order so that inserting a new field at the top is
	// cheap.
	l []headerField
	m map[string][]*headerField
}
```

but I think it should be a type of map[string][]string?

**Comment by emersion** [comment] 2019-04-18 10:17
Duplicate of https://github.com/emersion/go-imap/issues/236

**Closed by emersion** 2019-04-18 10:17 UTC
