### ISSUE TITLE
How to get the message content?

### ISSUE THREAD

**Issue by segura2010** [emersion/go-imap#72] opened 2016-11-21 10:42 UTC
Hi! Maybe it is not the site to ask this, but i dont know where to ask this.. 

I have been trying to get the message content, but i havent been able to do that.. Could someone tell if it is possible to do with this lib and how i could do that?

Im coding a simple terminal client in Go (http://i.imgur.com/4pPaB3T.png), I need to show the messages, at least the HTML/Text messages..

Thanks!

**Comment by emersion** [comment] 2016-11-21 14:19
Getting the message contents as plaintext or HTML is not that simple. Something like:
```go
seqset, _ := imap.NewSeqSet("")
seqset.AddRange(mbox.Messages, mbox.Messages)

messages := make(chan *imap.Message)
done = make(chan error, 1)
go func() {
	done <- c.Fetch(seqset, []string{"BODY[]"}, messages)
}()

for msg := range messages {
	literal := msg.GetBody("BODY[]")
	// Do something with this imap.Literal
}

if err := <-done; err != nil {
	log.Fatal(err)
}
```
would get the full MIME body.

If you only want the body, you have to first query the message BODYSTRUCTURE (see `imap.BodyStructureMsgAttr`, `imap.Message.BodyStructure`) then choose which part is the body (with a recursive function since it can be nested) and finally retrieve this part from the server (by asking for something like `BODY[1.3.2]`).

**Comment by segura2010** [comment] 2016-11-21 18:47
Thanks!! I will try it :)

**Comment by emersion** [comment] 2016-11-30 22:40
Closing, feel free to ask more questions if it doesn't work!

**Closed by emersion** 2016-11-30 22:40 UTC
Labels: invalid

**Comment by emersion** [comment] 2017-01-03 15:45
Note: I've finally created a library to easily parse and format mail messages: https://github.com/emersion/go-message

**Comment by segura2010** [comment] 2017-01-03 16:23
Thank you very much @emersion !! :D 

I have been busy, so i haven't been able to continue with little project, anyway, as soon as I have time for it I will check you library!

**Comment by segura2010** [comment] 2017-01-07 16:37
Hi @emersion , could you provide a simple example to use your new library with the imap library? :)
I cannot see how to use the messages from imap with the message type on the new lib.

Thank you very much!!

**Comment by emersion** [comment] 2017-01-07 17:05
Hi,

I created a new page on the wiki to explain this: https://github.com/emersion/go-imap/wiki/Fetching-messages#fetching-the-whole-message-body

If you have more questions, feel free to ask and I'll update the wiki page.

**Comment by segura2010** [comment] 2017-01-07 18:27
Hi!
Thank you very much!! Got it woking fine! :D

**Comment by genetix307** [comment] 2021-01-12 21:45
I know that it is has been awhile, but I've been attempting to implement this and am getting this error, any ideas what may be wrong?

cannot use section (type imap.BodySectionName) as type *imap.BodySectionName in argument to msg.GetBody

**Comment by stncrllr** [comment] 2021-04-26 08:38
> I know that it is has been awhile, but I've been attempting to implement this and am getting this error, any ideas what may be wrong?
> 
> cannot use section (type imap.BodySectionName) as type *imap.BodySectionName in argument to msg.GetBody
Try to make this change `r := msg.GetBody(&section)`

**Comment by robcanini** [comment] 2023-03-11 14:02
> I know that it is has been awhile, but I've been attempting to implement this and am getting this error, any ideas what may be wrong?
> 
> cannot use section (type imap.BodySectionName) as type *imap.BodySectionName in argument to msg.GetBody

```golang
section, _ := imap.ParseBodySectionName("BODY[]")
body := message.GetBody(section)
```

**Comment by swagftw** [comment] 2023-12-26 11:51
@emersion 
```go
errChan <- imapClient.Fetch(seqset, []imap.FetchItem{
			imap.FetchUid,
			imap.FetchEnvelope,
			imap.FetchFlags,
			imap.FetchInternalDate,
			imap.FetchBodyStructure,
			"BODY.PEEK[HEADER]",
			"BODY.PEEK[TEXT]<0.2048>",
			googleimap.XGMMsgID,
			googleimap.XGMThreadID,
		}, mails)
```

I have this fetch statement, but the problem is, the below code throws error `message: malformed MIME header line: --000000000000526933060acdb26e
` while creating the `mail.CreateReader(buffer)`. Is it even possible to read the body only? If yes, then how should create the reader that will read the body?
```go
// read the body
sec := imap.BodySectionName{}
sec.Specifier = imap.TextSpecifier
sec.Partial = []int{0, 2048}

buffer := email.GetBody(&sec)

reader, err := mail.CreateReader(buffer)
```
I am doing this because I dont want to fetch the whole message body, just the first 2048 octets. So that I can avoid the attachment.

**Comment by berti92** [comment] 2024-09-24 08:23
> Hi,
> 
> I created a new page on the wiki to explain this: https://github.com/emersion/go-imap/wiki/Fetching-messages#fetching-the-whole-message-body
> 
> If you have more questions, feel free to ask and I'll update the wiki page.

Could you provide a current link to the wiki? Currently, I get redirected to the main repository.
